backend:
  name: github
  repo: ko-lab/ko-lab-website # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/uploads" # repo: Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # published site: The src attribute for uploaded media will begin with /uploads
site_url: https://ko-lab.netlify.com
logo_url: images/ko-lab-robot-transparant-768x1024.png
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    extension: md
    preview_path: "/post/{{slug}}/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "List as an Event?", name: "event", widget: "boolean", default: false}
      - {label: "Tags (separate by comma)", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    extension: md
    preview_path: "/projects/{{slug}}/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Short description", name: "description", widget: "string"}
      - {label: "List as an Event?", name: "event", widget: "boolean", default: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Tags (separate by comma)", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}